---
title: "Hwk1"
author: "Minoo Ahmadi"
date: "February 8, 2017"
header-includes:
   - \usepackage{bbm}
output: pdf_document
---


```{r "setup", include=FALSE}
require("knitr")
opts_knit$set(root.dir = "~/gits/project/")
```


## Part I
### 1.
A mean of 35.17 (SD = 29.32) was found for the population.  A median of 27.5 indicates a right-skewness in the data, which is probably due to the maximum value of 150 for the subject with ID = 27. The variance is 860.15.

```{r}
getwd()
setwd("C:/Users/ahmadi/Documents/Courses/EDMS646/EDMS646_Spring_2017/Hwk1")
pop.data <- read.table ("population data 2017S.csv", header = TRUE, sep = ",")
summary(pop.data)

install.packages("pastecs")
install.packages("boot")
library(boot)
library(pastecs)
head(pop.data)
stat.desc(pop.data$commute, basic = FALSE)

```

### 2.
H_0: \mu = 30
H_1: \mu \neq 30

```{r}
samp.data <- read.table ("sample data 2017S.csv", header = TRUE, sep = ",")
summary(samp.data)
head(samp.data)
hist(samp.data$commute)
boxplot(samp.data$commute)
# df<- length(samp.data$ID)-1
# t.dist<- dt(samp.data$commute, df)
# plot(t.dist)
library(ggplot2)
ggplot(samp.data, aes(ID, commute)) + geom_point(size = 2) + geom_smooth(method = "lm")   # or: plot (samp.data$commute~samp.data$ID)

# t.test(samp.data$commute, alternative = "two.sided")
t.test(samp.data$commute, alternative = "two.sided", mu = 30)

z.test(samp.data$commute,alternative = "two.sided", mu = 30, sigma.x = 29.32835)
z.test(samp.data$commute,alternative = "two.sided", sigma.x = 29.32835)

```

```{r}
htn.data <- read.table ("Hypertension.csv", header = TRUE, sep = ",")
head(htn.data)
tail(htn.data)
stat.desc(htn.data$hyptension, basic = FALSE)
hist(htn.data$hyptension)
x<-seq(0,100,0.001) 
curve(dnorm(x, mean=mean(htn.data$hyptension), sd=sd(htn.data$hyptension)), add=TRUE)
boxplot(htn.data$hyptension)
qqline(htn.data$hyptension, distribution = qnorm,probs = c(0.25, 0.75))

ggplot(htn.data, aes(hyptension))+ geom_bar()+ facet_wrap(~ diet)
hist(htn.data$hyptension)
x<-seq(0,100,0.001) 
curve(dnorm(x, mean=mean(htn.data$hyptension), sd=sd(htn.data$hyptension)), add=TRUE)
boxplot(htn.data$hyptension)
qqline(htn.data$hyptension, distribution = qnorm,probs = c(0.25, 0.75))

# diet.1 <- htn.data[htn.data$diet==1]
diet.1 <- htn.data$hyptension[1:36]
# diet.2 <- htn.data$diet[htn.data$diet==2]
diet.2 <- htn.data$hyptension[37:72]
# data.diet1<- htn.data[diet.1]
# data.diet2<- htn.data[diet.2]
# stat.desc(data.diet1$hyptension, basic = FALSE)
stat.desc(diet.1, basic = FALSE)
stat.desc(diet.2, basic = FALSE)

hist(diet.1)
hist(diet.2)


x<-seq(0,100,0.001) 
curve(dnorm(x, mean=mean(htn.data$hyptension), sd=sd(htn.data$hyptension)), add=TRUE)
boxplot(diet.1)
boxplot(diet.2)

# t.test(diet.1, diet.2)
# t.test(htn.data$hyptension, htn.data$diet)
t.test(hyptension~diet, data= htn.data)

```
